import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Seblaks',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
      <meta name="viewport" content="width=device-width"/>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
