import './globals.css'
import { Inter } from 'next/font/google'
import { cookies, headers } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Seblaks',
  description: 'Generated by create next app',
}



export default  async function RootLayout({ children }) {
  // const getcookie = await 'undefined' ? 'light' : cookies().get('dark').value  
  // const b = cookies().get('dark').value

  return (
    <html lang="en"  >
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body className={`${inter.className} dark:text-white dark:bg-[#222] bg-gray-50` }>
        {children}
      </body>
    </html>
  )
}
